var hierarchy =
[
    [ "CustomLevelData", "struct_custom_level_data.html", null ],
    [ "HeadsetData", "class_headset_data.html", null ],
    [ "IPointerClickHandler", null, [
      [ "CloseOnClick", "class_close_on_click.html", null ]
    ] ],
    [ "MonoBehaviour", null, [
      [ "AddToken", "class_add_token.html", null ],
      [ "CameraController", "class_camera_controller.html", null ],
      [ "CameraScale", "class_camera_scale.html", null ],
      [ "ChallengeLevel", "class_challenge_level.html", null ],
      [ "CircleColour", "class_circle_colour.html", null ],
      [ "CloseOnClick", "class_close_on_click.html", null ],
      [ "CloudSelect", "class_cloud_select.html", null ],
      [ "DebugCanvasController", "class_debug_canvas_controller.html", null ],
      [ "DemoTriggerWild", "class_demo_trigger_wild.html", null ],
      [ "DemoTriggerWind", "class_demo_trigger_wind.html", null ],
      [ "DeviceCameraController", "class_device_camera_controller.html", null ],
      [ "ExtensionCustomLevel", "class_extension_custom_level.html", null ],
      [ "ExtensionDisplayController", "class_extension_display_controller.html", null ],
      [ "ExtensionHeadsetDisplay", "class_extension_headset_display.html", null ],
      [ "FireAnimationEvents", "class_fire_animation_events.html", null ],
      [ "FireIntroController", "class_fire_intro_controller.html", null ],
      [ "FireIntroEvents", "class_fire_intro_events.html", null ],
      [ "GameControllerBase", "class_game_controller_base.html", [
        [ "FireGameController", "class_fire_game_controller.html", null ],
        [ "PinwheelGameController", "class_pinwheel_game_controller.html", null ],
        [ "SquirrelGameController", "class_squirrel_game_controller.html", null ],
        [ "StarGameController", "class_star_game_controller.html", null ],
        [ "StoneGameController", "class_stone_game_controller.html", null ]
      ] ],
      [ "GuideButton", "class_guide_button.html", null ],
      [ "GuideImages", "class_guide_images.html", null ],
      [ "GuideToolsController", "class_guide_tools_controller.html", null ],
      [ "JarColour", "class_jar_colour.html", null ],
      [ "JarController", "class_jar_controller.html", null ],
      [ "LoadGame", "class_load_game.html", null ],
      [ "LogToggle", "class_log_toggle.html", null ],
      [ "Lumberjack", "class_lumberjack.html", null ],
      [ "MFClient", "class_m_f_client.html", null ],
      [ "MFServer", "class_m_f_server.html", null ],
      [ "MFThinkGear", "class_m_f_think_gear.html", null ],
      [ "ManageUserController", "class_manage_user_controller.html", null ],
      [ "MoveToImage", "class_move_to_image.html", null ],
      [ "MoveToTouch", "class_move_to_touch.html", null ],
      [ "NetworkReset", "class_network_reset.html", null ],
      [ "NewUser", "class_new_user.html", null ],
      [ "NextScene", "class_next_scene.html", null ],
      [ "ProgressCircle", "class_progress_circle.html", null ],
      [ "RestoreIcon", "class_restore_icon.html", null ],
      [ "SasquatchIntroController", "class_sasquatch_intro_controller.html", null ],
      [ "ServersDisplayController", "class_servers_display_controller.html", null ],
      [ "SessionHistoryController", "class_session_history_controller.html", null ],
      [ "SessionProgress", "class_session_progress.html", null ],
      [ "SessionView", "class_session_view.html", null ],
      [ "SquirrelIntroController", "class_squirrel_intro_controller.html", null ],
      [ "StarAnimationEvents", "class_star_animation_events.html", null ],
      [ "StarController", "class_star_controller.html", null ],
      [ "StarIntroController", "class_star_intro_controller.html", null ],
      [ "StoneController", "class_stone_controller.html", null ],
      [ "StoneLevel", "class_stone_level.html", null ],
      [ "TabletImageController", "class_tablet_image_controller.html", null ],
      [ "ThinkGearCanvasController", "class_think_gear_canvas_controller.html", null ],
      [ "ThinkGearData", "class_think_gear_data.html", null ],
      [ "ThinkGearDisplay", "class_think_gear_display.html", null ],
      [ "ThinkGearSignal", "class_think_gear_signal.html", null ],
      [ "ToolsController", "class_tools_controller.html", null ],
      [ "UserImage", "class_user_image.html", null ],
      [ "UserLoginGridController", "class_user_login_grid_controller.html", null ],
      [ "WindGirlPosition", "class_wind_girl_position.html", null ]
    ] ],
    [ "StateMachineBehaviour", null, [
      [ "SasquatchFallingState", "class_sasquatch_falling_state.html", null ],
      [ "SasquatchWaitingState", "class_sasquatch_waiting_state.html", null ],
      [ "SquirrelMovingState", "class_squirrel_moving_state.html", null ],
      [ "SquirrelMovingState3", "class_squirrel_moving_state3.html", null ],
      [ "SquirrelSpookedState", "class_squirrel_spooked_state.html", null ],
      [ "StarMoveState", "class_star_move_state.html", null ],
      [ "StoneEndingState", "class_stone_ending_state.html", null ],
      [ "StoneFallingState", "class_stone_falling_state.html", null ],
      [ "StoneMovingState", "class_stone_moving_state.html", null ],
      [ "StoneRestartState", "class_stone_restart_state.html", null ],
      [ "StoneStartingState", "class_stone_starting_state.html", null ],
      [ "StoneWaitingState", "class_stone_waiting_state.html", null ]
    ] ],
    [ "SyncHeadset", "class_sync_headset.html", null ],
    [ "SyncUser", "class_sync_user.html", null ],
    [ "UnityThinkGear", "class_unity_think_gear.html", null ]
];